//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCyclone.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_SysExceptionLog : Db_SysMsg
    {
        public int errorCode { get; set; }
        public string condtion { get; set; }
        public string source { get; set; }
        public string stackTrace { get; set; }
        public string targetSite { get; set; }
    }
}
