//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCyclone.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_SysDocFile
    {
        public int Id { get; set; }
        public string Db_SysDocId { get; set; }
        public string Db_SysFileId { get; set; }
    
        public virtual Db_SysDoc Db_SysDoc { get; set; }
    }
}
